"""The UI test driver Sightline injects.

Generated rather than shipped as a file so the audit-type list and the surface
navigation come from config instead of being hard-coded into somebody's repo.

The audit type spellings are the exact `XCUIAccessibilityAuditType` members, verified
against the Xcode 26.6 headers on 2026-08-31: `textClipped` (not `clippedText`), `trait`
(not `traits`), `sufficientElementDescription` (not `elementDescription`).
"""

from __future__ import annotations

from dataclasses import dataclass, field

DEFAULT_AUDIT_TYPES = (
    "contrast",
    "elementDetection",
    "hitRegion",
    "sufficientElementDescription",
    "dynamicType",
    "textClipped",
    "trait",
)


@dataclass(frozen=True)
class Surface:
    """One screen to reach and audit, and the taps that get there."""

    name: str
    taps: tuple[str, ...] = field(default_factory=tuple)
    wait_for: str | None = None

    @property
    def method_name(self) -> str:
        cleaned = "".join(c if c.isalnum() else "_" for c in self.name)
        return f"testSurface_{cleaned}"


def render_driver(
    surfaces: list[Surface],
    *,
    audit_types: tuple[str, ...] = DEFAULT_AUDIT_TYPES,
    class_name: str = "SightlineAudit",
) -> str:
    types = ",\n        ".join(f".{t}" for t in audit_types)
    methods = "\n\n".join(_render_method(s) for s in surfaces)
    return f"""// Generated by Sightline. Do not edit; edits are overwritten on every run.
//
// This file is injected into a scratch clone of the repository, never into the
// working tree it was copied from.

import XCTest

@MainActor
final class {class_name}: XCTestCase {{

    private static let auditTypes: XCUIAccessibilityAuditType = [
        {types},
    ]

    override func setUp() {{
        continueAfterFailure = true
    }}

    private static func name(of type: XCUIAccessibilityAuditType) -> String {{
        switch type {{
        case .contrast: return "contrast"
        case .elementDetection: return "elementDetection"
        case .hitRegion: return "hitRegion"
        case .sufficientElementDescription: return "sufficientElementDescription"
        case .dynamicType: return "dynamicType"
        case .textClipped: return "textClipped"
        case .trait: return "trait"
        default: return "unknown(\\(type.rawValue))"
        }}
    }}

    /// Scrolls until the control is hittable, then taps.
    ///
    /// Not defensive boilerplate: at large Dynamic Type sizes, controls that are
    /// on-screen at the default size are not. A driver that only taps works at the
    /// default size and silently fails the entire accessibility matrix.
    @discardableResult
    private func tap(_ app: XCUIApplication, _ identifier: String) -> Bool {{
        let element = app.descendants(matching: .any).matching(identifier: identifier).firstMatch
        for _ in 0..<10 {{
            if element.exists && element.isHittable {{
                element.tap()
                return true
            }}
            app.swipeUp()
        }}
        XCTFail("SIGHTLINE-UNREACHABLE|\\(identifier)")
        return false
    }}

    private func audit(_ app: XCUIApplication, screen: String) throws {{
        let shot = XCTAttachment(screenshot: app.screenshot())
        shot.name = "SIGHTLINE-SCREENSHOT-\\(screen)"
        shot.lifetime = .keepAlways
        add(shot)

        try app.performAccessibilityAudit(for: Self.auditTypes) {{ issue in
            let element = issue.element
            let identifier = element?.identifier ?? ""
            let label = element?.label ?? ""
            let frame = element.map {{ "\\($0.frame)" }} ?? "nil"
            let name = Self.name(of: issue.auditType)
            XCTContext.runActivity(
                named: "SIGHTLINE|\\(screen)|\\(name)|id=\\(identifier)|label=\\(label)"
                    + "|frame=\\(frame)|\\(issue.compactDescription)"
            ) {{ _ in }}
            return true  // handled — the harness reads the .xcresult, not pass/fail
        }}
    }}

{methods}
}}
"""


def _render_method(surface: Surface) -> str:
    taps = "\n".join(f'        tap(app, "{t}")' for t in surface.taps)
    wait = (
        f"        XCTAssertTrue(app.descendants(matching: .any)\n"
        f'            .matching(identifier: "{surface.wait_for}").firstMatch\n'
        f"            .waitForExistence(timeout: 15))\n"
        if surface.wait_for
        else ""
    )
    body = "\n".join(part for part in [taps, wait] if part)
    return f"""    func {surface.method_name}() throws {{
        let app = XCUIApplication()
        app.launch()
{body}        try audit(app, screen: "{surface.name}")
    }}"""
